### ISSUE TITLE
Updating workflows for shiny

### ISSUE THREAD

**Issue by javierggt** [sot/skare3#433]
I updated workflows the way I think reflects what is in the shiny conda channel. This is the list of packages. I also created PRs for all.

I can take care of merging most PRs. My suggestion is to start merging a few, especially the ones with build failures in the [dashboard](https://cxc.cfa.harvard.edu/mta/ASPECT/skare3/dashboard/)

The list was generated by looking at packages within skare3/pkg_defs that have a repository in acisops or sot. I removed acis packages that are forked in sot. There might be packages that should not have automated builds, especially packages being deprecated (sot/parse_cm? what else?)

```
arch_dependent:
  packages:
  - acisops/acisfp_check
  - acisops/acispy
  - acisops/bep_pcb_check
  - acisops/dea_check
  - acisops/dpa_check
  - acisops/fep1_actel_check
  - acisops/fep1_mong_check
  - acisops/psmc_check
  - sot/Chandra.Time
  - sot/Ska.Numpy
  - sot/aca_view
  - sot/acdc
  - sot/eng_archive
  - sot/kadi
  - sot/ska_sync
  - sot/skare3_tools
  - sot/sparkles
  - sot/testr
  - sot/xija

arch_independent:
  packages:
  - acisops/acis_thermal_check
  - acisops/backstop_history
  - sot/Chandra.Maneuver
  - sot/Quaternion
  - sot/Ska.DBI
  - sot/Ska.File
  - sot/Ska.Matplotlib
  - sot/Ska.ParseCM
  - sot/Ska.Shell
  - sot/Ska.Sun
  - sot/Ska.arc5gl
  - sot/Ska.astro
  - sot/Ska.ftp
  - sot/Ska.quatutil
  - sot/Ska.tdb
  - sot/acis_taco
  - sot/agasc
  - sot/annie
  - sot/chandra_aca
  - sot/cmd_states
  - sot/cxotime
  - sot/find_attitude
  - sot/hopper
  - sot/maude
  - sot/mica
  - sot/parse_cm
  - sot/proseco
  - sot/pyyaks
  - sot/ska_helpers
  - sot/ska_path
  - sot/starcheck
  - sot/tables3_api
  - sot/task_schedule
  - sot/watch_cron_logs
```

Tagging @jzuhone so he knows all PRs are summarized here.
